// import { Geist, Geist_Mono } from "next/font/google";
import Footer from "../components/Footer";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Plus_Jakarta_Sans } from 'next/font/google'

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // customize as needed
  display: 'swap',
  variable: '--font-plus-jakarta',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${plusJakartaSans.className} `}
      ><Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
